# Generated by Django 4.1 on 2023-06-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_record', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
