# Generated by Django 4.1 on 2023-06-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_record', '0007_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='impression',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
