# Generated by Django 4.1 on 2023-06-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading_record', '0009_record_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='poster',
            new_name='user',
        ),
    ]
