# Generated by Django 4.2.2 on 2023-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_record', '0011_record_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
