# Generated by Django 4.1 on 2023-06-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_record', '0004_account_delete_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
