# Generated by Django 4.1 on 2023-06-06 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reading_record', '0006_alter_account_first_name_alter_account_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('first_page', models.IntegerField()),
                ('final_page', models.IntegerField()),
                ('impression', models.TextField()),
                ('posted_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField()),
            ],
        ),
    ]
