# Generated by Django 4.2.2 on 2023-06-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reading_record', '0010_rename_poster_record_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
